workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-4
  replicaCount: 1
  pythonPackageSpec:
    executorImageUri: us-docker.pkg.dev/vertex-ai/training/tf-cpu.2-8:latest
    packageUris: gs://spectrain//spectrain_csv_dnn/spectrain_csv_dnn_trainer-0.1.tar.gz
    pythonModule: trainer.task
    args:
    - --train_data_path=gs://spectrain//bhavani/csv_split/train.csv
    - --eval_data_path=gs://spectrain//bhavani/csv_split/valid.csv
    - --output_dir=gs://spectrain//spectrain_csv_dnn/trained_model_20230614_165149
    - --num_epochs=10
    - --train_examples=4000
    - --eval_steps=100
    - --batch_size=32
