workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-4
  replicaCount: 1
  pythonPackageSpec:
    executorImageUri: us-docker.pkg.dev/vertex-ai/training/tf-cpu.2-8:latest
    packageUris: gs://spectrain//spectrain_cnn/spectrain_proc_img_trainer-0.1.tar.gz
    pythonModule: trainer.task
    args:
    - --train_data_path=gs://spectrain//bhavani/train_images
    - --eval_data_path=gs://spectrain//bhavani/valid_images
    - --output_dir=gs://spectrain//spectrain_cnn/trained_model_20230614_184948
    - --num_epochs=10
    - --train_examples=10000
    - --eval_steps=100
    - --batch_size=32
